# this is a CICD pipeline which builds and pushes a Docker image from Azure Devops Repo to a Github Container Registry
# replace dockerRegistryServiceConnection with your Service Connection (set up in Project Settings)
# replace YourPackage with your chosen package name (which you can then pull from the Container Registry)

trigger:
  branches:
   include:
    - main
  paths:
    exclude:
      - '**/*.md'
      - '**/*.yml'

pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: buildAndPush
    containerRegistry: 'dockerRegistryServiceConnection' 
    repository: 'GithubUserName/YourPackage' 
    dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: echo 'YourPackage Docker image built and pushed successfully!'
  displayName: 'Happy Days'
