# This is a CICD pipeline which builds and pushes a Docker image from Azure DevOps Repo to a GitHub Container Registry
# This version does the build and push seperately so you can you an Azure Artifact nuget feed
# You will need to have a `FEED_ACCESSTOKEN` variable containing a Personal Access Token with permission to your Azure Artifact nuget feed account 
## You will only need the Packaging Read permission
# replace dockerRegistryServiceConnection with your Service Connection (set up in Project Settings)
# replace YourPackage with your chosen package name (which you can then pull from the Container Registry)

trigger:
  branches:
   include:
    - main
  paths:
    exclude:
      - '**/*.md'
      - '**/*.yml'

pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: Docker@2
  displayName: Build
  inputs:
    command: build
    containerRegistry: 'dockerRegistryServiceConnection' 
    repository: 'GithubUserName/YourPackage' 
    dockerfile: '**/Dockerfile'
    tags: 'latest'
    arguments: '--build-arg FEED_ACCESSTOKEN=$(FEED_ACCESSTOKEN)'

- task: Docker@2
  displayName: Push Docker image
  inputs:
    command: push
    containerRegistry: 'dockerRegistryServiceConnection' 
    repository: 'GithubUserName/YourPackage' 
    dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: echo 'YourPackage Docker image built and pushed successfully!'
  displayName: 'Happy Days'
